### ISSUE TITLE
RE: Help

### ISSUE THREAD

**Issue by JonnyUK** [danielepantaleone/php-rcon#1]
Hey,

Sorry I'm an ameture when it comes to PHP, what must I do to be able to send rcon commands to my server from my webserver?

Regards,
JonnyUK
http://drunknoobs.com

**Comment by danielepantaleone** [comment]
You would need to create yourself a webpanel which provides the interaction with the gameserver. This library is just the "final" part, so you can used this one but you would need a lot more.

**Comment by JonnyUK** [comment]
I'm trying to modify echelon so that I can slap players in game etc so how
could I use this to send rcon commands to the server? Do you do freelance
work because if you can help me I'm more than happy to pay for your
services

**Comment by danielepantaleone** [comment]
Echelon already has an RCON interface so you don't need this if you are already using Echelon. I don't do freelance jobs sorry.
